apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-microservice-deployment
  labels:
    app: secure-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-microservice
  template:
    metadata:
      labels:
        app: secure-microservice
    spec:
      containers:
      - name: secure-microservice
        image: gkumi94/secure-microservice:latest
        ports:
        - containerPort: 8080
