apiVersion: v1
kind: Service
metadata:
  name: secure-microservice-service
spec:
  selector:
    app: secure-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
